# Generated by Django 4.2.3 on 2026-04-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_alter_choice_id_alter_course_id_alter_course_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('programming', 'Programming'), ('web', 'Web Development'), ('data', 'Data Science'), ('cloud', 'Cloud Computing'), ('design', 'Design'), ('devops', 'DevOps'), ('other', 'Other')], default='programming', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='exam_time_limit',
            field=models.IntegerField(default=0, help_text='Time limit for exam in minutes. 0 = no limit.'),
        ),
        migrations.AddField(
            model_name='course',
            name='passing_score',
            field=models.IntegerField(default=80, help_text='Minimum score to pass the exam.'),
        ),
        migrations.AddField(
            model_name='submission',
            name='attempt_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='submission',
            name='passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='time_taken_seconds',
            field=models.IntegerField(default=0, help_text='How many seconds the student took'),
        ),
        migrations.AddField(
            model_name='submission',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(default='online course', max_length=100),
        ),
    ]
