# Generated by Django 4.2.3 on 2026-04-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0004_learner_last_activity_date_learner_streak_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='social_link',
            field=models.URLField(blank=True),
        ),
    ]
