# Generated by Django 4.2.3 on 2026-04-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0005_alter_learner_social_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='is_rated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
